apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: argocd-appset-ext
  labels:
    tab: "ApplicationSet"
    icon: "fa-files"
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
    - web:
        url: https://github.com/niteshlaller89/argocd-flow/blob/main/ui/dist/extension.tar
