apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - name: guestbook-one
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/niteshlaller89/argocd-flow.git
        targetRevision: main
        path: app
      destination:
        server: '{{.url}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
